### ISSUE TITLE
Clarification needed: Creating a Repo for our Team

### ISSUE THREAD

**Issue by sadieamato** [comp426-2023-spring/a99#4]
#### URL of file with confusing thing

https://github.com/comp426-2023-spring/a99/blob/main/CHECKLIST.md#a99-checklist

#### Line number of confusing thing

5

#### What is confusing?

"Create a repository in your team using this template repo"
We are unsure how to do this. When we go to our team's repositories, there is no button to add a repository. If we try to create a repo from the template, there is no option for creating it inside our team.

#### What do you think the confusing thing means?

I think it means that we need a repo directly inside our team.

#### What did you read to try to understand better what is happening and solve the issue?

Googled "how to add a repository to a team", etc. Consulted my team member's and they weren't sure either.

**Comment by daqichen** [comment]
@sadieamato This [article](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#inviting-a-team-or-person) should help you how to add your Team to access the repo you have created!

**Comment by sadieamato** [comment]
Thank you! I tried following those steps, but when I use the a99 template and go to collaborator settings, I cannot add a team, I can only add individuals. Is just adding our team members good enough? @daqichen 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/77795947/227609680-dec715f6-240d-4fb1-8be1-0798fe0de855.png">

**Comment by daqichen** [comment]
@sadieamato is [this](https://github.com/sadieamato/a99-TeamNoTeam) the repo? It should be under the [class org](https://github.com/comp426-2023-spring) instead of your own github username. Did you accept the assignment invite to create the repo or just forked the template repo

**Comment by daqichen** [comment]
Go to https://github.com/comp426-2023-spring

Create a New Repository

Choose a99 as your template

**Comment by sadieamato** [comment]
Thank you! Yes, I was going directly to a99 to use it as a template which doesn't work. Got it working now.
