### ISSUE TITLE
Clarification needed: Submitting a99 when API keys Needed

### ISSUE THREAD

**Issue by ajaygandecha** [comp426-2023-spring/a99#6]
Hello Professor @jdmar3,

I had a quick question regarding the submission process for `a99`. Currently, our project uses a few external dependencies that require API keys, and we have been storing these API keys in a hidden secrets file (`.env`) locally. Since these API keys are sensitive, we cannot push the `.env` file into our GitHub repository.

When working with these APIs and API keys, are we able to potentially send this file to you or the grader when needed, or will there be a separate process for this when submitting our projects?

We plan to live host our completed site, so its functionality would be perfectly visible even without the API keys - however, when a grader attempts to test out the project locally on their computer, it may not work correctly.

Thank you for the help!

**Comment by ajaygandecha** [comment]
(Not sure why the documentation tag was added - unable to remove it either, sorry about that)

**Comment by jdmar3** [comment]
The easiest thing would be to send the env file to me so I can spin it up. But, make sure also that in your repo documentation you link to the live instance. I would also love to see how you have articulated/configured the environment for your live instance.

**Comment by ajaygandecha** [comment]
Great, thank you so much -- will make sure to do both!
